#!/usr/bin/env bash
# Install and configure HAProxy 1.6 on a new Ubuntu 16.04 server

apt-get -y update
apt-get -y install 'haproxy=1.6.*'

cat >> /etc/haproxy/haproxy.cfg << EOF
backend web-backend
	balance roundrobin
	mode http
	server 30489-web-01 54.90.17.84 check
	server 30489-web-02 100.26.255.122 check
frontend web-frontend
	bind *:80
	mode http
	default_backend web-backend
EOF

service haproxy restart
