#!/usr/bin/env bash
# Install and configure HAProxy 

apt-get -y update
apt-get -y install haproxy

cat >> /etc/haproxy/haproxy.cfg << EOF
backend backend
	balance roundrobin
	mode http
	server 30489-web-01 54.90.17.84 check
	server 30489-web-02 100.26.255.122 check
frontend frontend
	bind *:80
	mode http
	default_backend web-backend
EOF

service haproxy restart
