#!/usr/bin/env bash                                                             
#start apache2 inside docker                                                     
echo "Hello Holberton" >> /etc/apache2.conf
service apache2 start
